### ISSUE TITLE
Softlocks N64VC in general at boot

### ISSUE THREAD

**Issue by MysticFlipFlop** [WiiDatabase/Padcon-Plugin-Mod#1]
i tried with 3 games:
Donkey Kong 64 (official)
Banjo Kazooie (inject)
Paper Mario (official)
-softlock at boot

deleted padcon and they finally worked

**Comment by Brawl345** [comment]
Can you try this version please and tell me if it works? 
[padcon.zip](https://github.com/WiiDatabase/Padcon-Plugin-Mod/files/9592648/padcon.zip)

**Comment by MysticFlipFlop** [comment]
sure

**Comment by MysticFlipFlop** [comment]
omg, it works now. no softlock

**Comment by Brawl345** [comment]
Great, thanks for the feedback! I will prepare a bugfix release v1.2.2.

**Comment by Brawl345** [comment]
Here you go: https://github.com/WiiDatabase/Padcon-Plugin-Mod/releases/tag/v1.2.2
