### ISSUE TITLE
Console hangs on loading splash when exiting Replay: VHS Is Not Dead

### ISSUE THREAD

**Issue by vaguerant** [WiiDatabase/Padcon-Plugin-Mod#3]
Not much to describe here; issue occurs whether you exit immediately on boot (e.g. from the Neko Entertainment splash screen) or later. Console requires a hard power-off to get out of the loading loop, and generates a crash log (attached below).

Removing this plugin from Aroma prevents the issue from occurring.

**Game tested:**
```
00050000-101E2D00
REPLAY : VHS IS NOT DEAD
WUP-P-BREP
```

**Console:**
5.5.5 E
Aroma Beta-4 (2022-09-19)
Padcon-Plugin-Mod v1.2.2 (0d8ccb4)

**Crash log:**
[87.log](https://github.com/WiiDatabase/Padcon-Plugin-Mod/files/9647251/87.log)

**Comment by Brawl345** [comment]
Thanks for reporting. This is an "issue" in Aroma that will be fixed there in the next/one of the next version(s).
