### ISSUE TITLE
Making a screenshot with the Aroma plug-in flashes the screen briefly

### ISSUE THREAD

**Issue by Invictaz** [WiiDatabase/Padcon-Plugin-Mod#7]
Making a screenshot with the Screenshot plug-in included in Aroma by Maschell turns on the gamepad screen briefly when you press the TV button.

Expected behavior is that the screen should stay off.

**Comment by Brawl345** [comment]
Not a bug in the Padcon Plugin. Maybe the screen has to be turned on to make a screenshot?

**Comment by Invictaz** [comment]
It isn't said that it should be turned on, after all it's just a framebuffer dump which is not the same as an LCD that is lit. Maybe @Maschell knows?
