### ISSUE TITLE
Battery icon stays blue when gamepad is turned off

### ISSUE THREAD

**Issue by Invictaz** [WiiDatabase/Padcon-Plugin-Mod#8]
When you press the button combination the charging or battery icon stays on in either orange or blue. I don't remember exactly but on the old padcon under WiiU Plug-in System it was totally off, which is better for dark environments late at night 🌙 

Expected behavior: have the option to turn off all leds either by #6

**Comment by Brawl345** [comment]
Not possible, it's a system limitation. The old padcon did the same thing, it's the same code.

**Comment by Invictaz** [comment]
Quite sad to hear that. Then I have to tape over the led.
